services:
  # Webアプリケーション
  - type: web
    name: text-improvement-app
    runtime: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "cd project && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: text-improvement-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false

  # PostgreSQLデータベース
  - type: pserv
    name: text-improvement-db
    plan: free
